server:
  port: 8222

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: teacher
          uri: lb://teacher
          predicates:
            - Path=/api/teachers/**
        - id: course
          uri: lb://course
          predicates:
            - Path=/api/courses/**
        - id: student
          uri: lb://student
          predicates:
            - Path=/api/students/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0   # 100% sampling for demo
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}] %m"