spring:
  application:
    name: student

  datasource:
    url: jdbc:mysql://localhost:3306/student_vlad_micro?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 19649072Sever

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0   # 100% sampling for demo
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}] %m"